watch-later-directory="~/.cache/mpv/"
mute=no
sub-auto=fuzzy # do not require exact filename for subs
ytdl-raw-options=ignore-config=,sub-format=en,write-sub=
# disable terminal alltogether (for mpv not to run in the background)
terminal=no
force-window=yes
# geometry=100%:0% # force placement at the end of the screen
# layout=topbar
screenshot-directory="~/Pictures/google-photos/screenshots/mpv" # environmental variables don't work
save-position-on-quit=yes
autofit-larger=900x500
# script-opts=osc-layout=bottombar
# --sub-italic=yes
# --osd-italic=yes
# sub-font-size=40
# osd-font-size=40
--no-sub-visibility
# --showfullscreen=no
ytdl-format=bestvideo[height<=?720]+bestaudio/best

[1080p]
ytdl-format=bestvideo[height<=?1080]+bestaudio/best

[720p]
ytdl-format=bestvideo[height<=?720]+bestaudio/best

[480p]
ytdl-format=bestvideo[height<=?480]+bestaudio/best

[360p]
ytdl-format=bestvideo[height<=?360]+bestaudio/best

[audio]
profile-desc=Audio window settings
autofit-larger=300x300
# --load-osd-console=<yes|no>
# --osc=yes
# vidscale=no
# osc-visibility=always
idle=once
geometry=100%:100% # force placement at the end of the screen
osc=yes
loop-file=inf
# layout=box
# seekbarstyle=diamond

[small]
ytdl-format=bestvideo[height<=?360]+bestaudio/best
autofit-larger=500x500
geometry=100%:100% # force placement at the end of the screen
