#!/bin/sh

[ "$1" = "-a" ] && subdir="articles-highlights" || subdir="readlater"

dir="$HOME/personal/$subdir"
pdf_file="$dir/$(echo "$QUTE_TITLE" | sed 's/\///g').pdf"

echo "print --pdf \"$pdf_file\"" >>"$QUTE_FIFO"

# move to a sub-directory (tags)
tags="$(find "$dir" -type d -mindepth 1 -maxdepth 1 -exec basename {} \;)"
if [ -n "$tags" ]; then
	tag="$(echo "$tags" | menu-wrapper -p 'tag')"
	if [ -n "$tag" ]; then
		new_path="$dir/$tag/$(basename "$pdf_file")"
		mv "$pdf_file" "$new_path"
        pdf_file="$new_path"
	fi
fi

if [ "$1" = "-a" ]; then
	while [ ! -f "$pdf_file" ]; do
		sleep 0.1
	done
	xournalpp "$pdf_file"
fi
