font_family      Menlo
bold_font        auto
italic_font      auto
bold_italic_font auto
force_ltr yes

cursor_blink_interval 0
enable_audio_bell no
confirm_os_window_close 1
tab_bar_style separator

font_size 14
shell_integration  no-cursor
remember_window_size  no
initial_window_width  900
initial_window_height 800

# background_opacity 0.9
# hide_window_decorations yes


map alt+c copy_to_clipboard
map alt+v paste_from_clipboard

macos_option_as_alt yes

background            #000000
foreground            #ffffff
#cursor #000000
#selection_background  #000000
#color0                #ff0000
#color8                #3e953a
#color1                #daa520
#color9                #0000ff
#color2                #a00095
#color10               #3e953a
#color3                #bbbbbb
#color11
#color4                #000000
#color12               #ff0000
#color5                #3e953a
#color13               #daa520
#color6                #0000ff
#color14               #a00095
#color7                #3e953a
#color15               #ffffff

# background #ffffff
# foreground #000000
# cursor #000000
# selection_background #b4d5ff
# color0 #000000
# color8 #545753
# color1 #cc0000
# color9 #ef2828
# color2 #4e9a05
# color10 #8ae234
# color3 #c4a000
# color11 #fce94e
# color4 #3464a4
# color12 #719ecf
# color5 #74507a
# color13 #ad7ea7
# color6 #05989a
# color14 #34e2e2
# color7 #d3d7cf
# color15 #ededec
# selection_foreground #ffffff


# BEGIN_KITTY_THEME
# Default
# include current-theme.conf
# END_KITTY_THEME
#
#

# # Monochrome theme
# foreground #FFFFFF
# background #000000
# # The sixteen terminal colors
# color0 #000000
# color1 #FFFFFF
# color2 #FFFFFF
# color3 #FFFFFF
# color4 #FFFFFF
# color5 #FFFFFF
# color6 #FFFFFF
# color7 #FFFFFF
# color8 #808080
# color9 #FFFFFF
# color10 #FFFFFF
# color11 #FFFFFF
# color12 #FFFFFF
# color13 #FFFFFF
# color14 #FFFFFF
# color15 #FFFFFF
#
#
#
include ./gruvbox-theme.conf
